{
    "name": "Crapo: Automaton UI",
    "version": "12.0.3.0.0",
    "category": "Crapo Automata & Workflows",
    "author": "Article714",
    "license": "LGPL-3",
    "website": "https://www.article714.org",
    "summary": """ Add UI to crapo automaton""",
    "depends": ["crapo_automaton"],
    "data": [
        "actions/window_actions.xml",
        "views/crapo_menus.xml",
        "views/crapo_automaton_state_views.xml",
        "views/crapo_automaton_transition_views.xml",
        "views/crapo_automaton_action_views.xml",
        "views/crapo_automaton_views.xml",
        "views/crapo_automaton_condition_views.xml",
    ],
    "installable": True,
    "images": [],
    "application": True,
}
